name: CI

on:
  push:
    branches: [ main, feature/results-pop-up ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask selenium webdriver-manager
        pip install python-dateutil
        pip install -r requirements.txt || true
    - name: Start Flask app
      run: |
        nohup python app.py &
        sleep 5
    - name: Run unit tests
      run: |
        python -m unittest Unit_test.py
    - name: Run UI tests
      env:
        SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub
      run: |
        python test_ui.py
